# Copyright (c) 2016-2019 Christian Friedli <mail@christainfriedli.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Cloud Monk
site_description: TechBlog
site_author: Christian Friedli
site_url: http://cloudmonk.ch

# Repository
repo_name: cfriedli/cloudmonk
repo_url: https://github.com/cfriedli/cloudmonk
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Christian Friedli'

# Configuration
# Configuration
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/Ansible_logo.png'

  color: white
  features:
    tabs: true
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: White
    accent: White
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Ansible Notes:
    - Introduction:                            'index.md'
    - Introducing Ansible:                     'ansible/Introducing-Ansible.md'
    - Deplaying Ansible:                       'ansible/Deploying-Ansible.md'
    - Implementing Playbooks:                  'ansible/Implementing-Playbooks.md'
    - Managing Varables and Facts:             'ansible/Managing-Veriables-and-Facts.md'
    - Implementing Task Control:               'ansible/Implementing-Task-Control.md'
    - Simplifizing Playbooks with roles:       'ansible/simplifizing-playbooks-with-roles.md'
    - Ansible Modules:                         'ansible/modules.md'
    - References:                              'ansible/References.md'
  - API Notes:
    - Introduction:  'api-notes/api-index.md'
    - Interacting with RESTful API's (URI):    'api-notes/URI-API.md'
  - AWS Notes:
    - Introduction: 'aws/aws-index.md'
  - SystemD Notes:
    - Introduction: 'systemd/systemd-index.md'
    - systemctl:    'systemd/systemd-systemctl.md'
    - Units:
        systemd.mount:      'systemd/systemd-mount.md'

# Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
# Customization
extra:
  social:
    - type: github
      link: https://github.com/cfriedli
    - type: twitter
      link: https://twitter.com/chgumucio
    - type: linkedin
      link: https://www.linkedin.com/in/christian-friedli-b36072118/

extra_css:
 - 'stylesheets/unibe.css'

